spring:
  datasource:
    password: Emids123
    url: jdbc:mysql://localhost:3306/employee_example?useSSL=false
    username: root
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8081
